-- First, delete related records in the ORDER_LINE table
DELETE FROM ORDER_LINE WHERE ORDER_ID IN (SELECT ORDER_ID FROM ORDERT WHERE CUSTOMER_ID = 10001);

-- Then, delete records in the ORDERT table
DELETE FROM ORDERT WHERE CUSTOMER_ID = 10001;

-- Finally, delete the customer record in the CUSTOMER table
DELETE FROM CUSTOMER WHERE CUSTOMER_ID = 10001;

SELECT * FROM CUSTOMER;
SELECT * FROM ORDERT;
SELECT * FROM ORDER_LINE;