WITH NumberOfOrder AS (
  SELECT ol.PRODUCT_ID, COUNT(o.ORDER_ID) AS NUMBER_OF_ORDERS
  FROM ORDER_LINE ol
  JOIN ORDERT o ON ol.ORDER_ID = o.ORDER_ID
  GROUP BY ol.PRODUCT_ID
)

SELECT p.PRODUCT_ID, p.PRODUCT_DESCRIPTION
FROM PRODUCT p
JOIN NumberOfOrder noo
ON p.PRODUCT_ID = noo.PRODUCT_ID
WHERE noo.NUMBER_OF_ORDERS = (
    SELECT MAX(NUMBER_OF_ORDERS)
    FROM NumberOfOrder
);