WITH ProductTotalQuantity AS (
    SELECT ol.PRODUCT_ID, SUM(ol.ORDERED_QUANTITY) AS TOTAL_QUANTITY
    FROM ORDER_LINE ol
    GROUP BY ol.PRODUCT_ID
)

SELECT p.PRODUCT_ID, p.PRODUCT_DESCRIPTION
FROM PRODUCT p
JOIN ProductTotalQuantity ptq
ON p.PRODUCT_ID = ptq.PRODUCT_ID
WHERE ptq.TOTAL_QUANTITY = (
    SELECT MAX(TOTAL_QUANTITY)
    FROM ProductTotalQuantity
);