SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, COUNT(o.ORDER_ID) AS ORDER_COUNT
FROM CUSTOMER c
LEFT JOIN ORDERT o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
HAVING COUNT(o.ORDER_ID) > 0
ORDER BY ORDER_COUNT DESC
LIMIT 3;